/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui_visual;
import fachada.Fachada;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nit
 */
public class VentanaDocente extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaDocente.class.getName());
    private Fachada fachada;
    /**
     * Creates new form VentanaDocente
     */
    public VentanaDocente() {
        initComponents();
        fachada = new Fachada();
        btnFlatLafDocente(btnGuardarCambios, "Guardar Cambios");
        btnFlatLafDocente(btnVerHistorial, "Ver Historial");
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }
    
    private void btnFlatLafDocente(javax.swing.JButton btn, String texto){
        btn.setText(texto);
        btn.setBackground(new java.awt.Color(50, 50, 50));
        btn.setForeground(java.awt.Color.WHITE);
        btn.putClientProperty(com.formdev.flatlaf.FlatClientProperties.BUTTON_TYPE, com.formdev.flatlaf.FlatClientProperties.BUTTON_TYPE_ROUND_RECT);
        btn.putClientProperty(com.formdev.flatlaf.FlatClientProperties.STYLE, "arc: 999");
    }
    
    public void cargarCursoCbx (String ciDocente){
        cbxCurso.removeAllItems();
        
        ArrayList<String> cursos = fachada.nombresCursosDocente(ciDocente);
        if(cursos != null){
            for(int i = 0; i < cursos.size(); i++ ){
                String nombreCurso = cursos.get(i);
                cbxCurso.addItem(nombreCurso);
            }
            if(cbxCurso.getItemCount()>0){
                String primeraSeleccion = (String) cbxCurso.getItemAt(0);
                String[] partes = primeraSeleccion.split(" - ");
                int idPrimerCurso = Integer.parseInt(partes[0].trim());
                cargarTablaEstudiantes(idPrimerCurso);
            }
        }
    }
    
    public void cargarNomApeDocente (String nom, String ape){
        lblNomApe.setText(nom + " " + ape);
    }
    
    public void cargarTablaEstudiantes (int idCurso){
        DefaultTableModel model = (DefaultTableModel) tblListaEstudiante.getModel();
        model.setRowCount(0);
        ArrayList<String[]> listaEstudiantes = fachada.obtenerEstudiantePorCurso(idCurso);
        if(listaEstudiantes != null){
            for(int i=0; i<listaEstudiantes.size(); i++){
                model.addRow((Object[]) listaEstudiantes.get(i));
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlVentana = new javax.swing.JPanel();
        pnlBarraSuperior = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblNomApe = new javax.swing.JLabel();
        pnlPanelSuperior = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lblAnioLectivo = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbxCurso = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        lblAsignaturaSel = new javax.swing.JLabel();
        pnlCentral = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListaEstudiante = new javax.swing.JTable();
        pnlInferior = new javax.swing.JPanel();
        btnGuardarCambios = new javax.swing.JButton();
        btnVerHistorial = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlVentana.setBackground(java.awt.Color.lightGray);
        pnlVentana.setPreferredSize(new java.awt.Dimension(1280, 720));

        pnlBarraSuperior.setBackground(java.awt.Color.black);
        pnlBarraSuperior.setPreferredSize(new java.awt.Dimension(1280, 80));

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 70)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText("SGA");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("SISTEMA DE GESTIÓN ACADÉMICA");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setText("Bienvenido/a Docente");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblNomApe.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        lblNomApe.setForeground(java.awt.Color.white);
        lblNomApe.setText("\"Nombre Apellido\"");
        lblNomApe.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pnlBarraSuperiorLayout = new javax.swing.GroupLayout(pnlBarraSuperior);
        pnlBarraSuperior.setLayout(pnlBarraSuperiorLayout);
        pnlBarraSuperiorLayout.setHorizontalGroup(
            pnlBarraSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBarraSuperiorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 611, Short.MAX_VALUE)
                .addGroup(pnlBarraSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(lblNomApe))
                .addGap(86, 86, 86))
        );
        pnlBarraSuperiorLayout.setVerticalGroup(
            pnlBarraSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBarraSuperiorLayout.createSequentialGroup()
                .addGroup(pnlBarraSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(0, 4, Short.MAX_VALUE))
            .addGroup(pnlBarraSuperiorLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNomApe)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlPanelSuperior.setBackground(java.awt.Color.lightGray);
        pnlPanelSuperior.setForeground(java.awt.Color.black);
        pnlPanelSuperior.setPreferredSize(new java.awt.Dimension(1280, 90));

        jLabel4.setFont(new java.awt.Font("Yu Gothic", 1, 15)); // NOI18N
        jLabel4.setForeground(java.awt.Color.black);
        jLabel4.setText("Año lectivo:");

        lblAnioLectivo.setFont(new java.awt.Font("Yu Gothic", 1, 15)); // NOI18N
        lblAnioLectivo.setForeground(java.awt.Color.black);
        lblAnioLectivo.setText("2026");

        jLabel5.setFont(new java.awt.Font("Yu Gothic", 1, 15)); // NOI18N
        jLabel5.setForeground(java.awt.Color.black);
        jLabel5.setText("Seleccionar Curso:");

        cbxCurso.setBackground(java.awt.Color.gray);
        cbxCurso.setForeground(java.awt.Color.black);
        cbxCurso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxCurso.addActionListener(this::cbxCursoActionPerformed);

        jLabel6.setFont(new java.awt.Font("Yu Gothic", 1, 15)); // NOI18N
        jLabel6.setForeground(java.awt.Color.black);
        jLabel6.setText("Asignatura:");

        lblAsignaturaSel.setFont(new java.awt.Font("Yu Gothic", 1, 15)); // NOI18N
        lblAsignaturaSel.setForeground(java.awt.Color.black);
        lblAsignaturaSel.setText("Selecciona un curso");

        javax.swing.GroupLayout pnlPanelSuperiorLayout = new javax.swing.GroupLayout(pnlPanelSuperior);
        pnlPanelSuperior.setLayout(pnlPanelSuperiorLayout);
        pnlPanelSuperiorLayout.setHorizontalGroup(
            pnlPanelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPanelSuperiorLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAnioLectivo, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cbxCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAsignaturaSel)
                .addContainerGap(415, Short.MAX_VALUE))
        );
        pnlPanelSuperiorLayout.setVerticalGroup(
            pnlPanelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPanelSuperiorLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pnlPanelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblAnioLectivo)
                    .addComponent(jLabel5)
                    .addComponent(cbxCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(lblAsignaturaSel))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pnlCentral.setBackground(java.awt.Color.black);
        pnlCentral.setPreferredSize(new java.awt.Dimension(1280, 450));

        tblListaEstudiante.setBackground(java.awt.Color.gray);
        tblListaEstudiante.setFont(new java.awt.Font("Yu Gothic", 1, 15)); // NOI18N
        tblListaEstudiante.setForeground(java.awt.Color.black);
        tblListaEstudiante.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Cédula", "Nombre", "Apellido", "Nueva Calificación", "Observación"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblListaEstudiante);

        javax.swing.GroupLayout pnlCentralLayout = new javax.swing.GroupLayout(pnlCentral);
        pnlCentral.setLayout(pnlCentralLayout);
        pnlCentralLayout.setHorizontalGroup(
            pnlCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCentralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1268, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlCentralLayout.setVerticalGroup(
            pnlCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCentralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlInferior.setBackground(java.awt.Color.lightGray);
        pnlInferior.setPreferredSize(new java.awt.Dimension(1280, 82));

        btnGuardarCambios.setBackground(java.awt.Color.darkGray);
        btnGuardarCambios.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnGuardarCambios.setText("Guardar Cambios");
        btnGuardarCambios.addActionListener(this::btnGuardarCambiosActionPerformed);

        btnVerHistorial.setBackground(java.awt.Color.darkGray);
        btnVerHistorial.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnVerHistorial.setText("Ver Historial");
        btnVerHistorial.addActionListener(this::btnVerHistorialActionPerformed);

        javax.swing.GroupLayout pnlInferiorLayout = new javax.swing.GroupLayout(pnlInferior);
        pnlInferior.setLayout(pnlInferiorLayout);
        pnlInferiorLayout.setHorizontalGroup(
            pnlInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInferiorLayout.createSequentialGroup()
                .addContainerGap(1016, Short.MAX_VALUE)
                .addComponent(btnVerHistorial)
                .addGap(18, 18, 18)
                .addComponent(btnGuardarCambios)
                .addGap(23, 23, 23))
        );
        pnlInferiorLayout.setVerticalGroup(
            pnlInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInferiorLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(pnlInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarCambios, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVerHistorial, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlVentanaLayout = new javax.swing.GroupLayout(pnlVentana);
        pnlVentana.setLayout(pnlVentanaLayout);
        pnlVentanaLayout.setHorizontalGroup(
            pnlVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVentanaLayout.createSequentialGroup()
                .addGroup(pnlVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlBarraSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlPanelSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlCentral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlInferior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlVentanaLayout.setVerticalGroup(
            pnlVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVentanaLayout.createSequentialGroup()
                .addComponent(pnlBarraSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlPanelSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlCentral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlInferior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlVentana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlVentana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCursoActionPerformed
        String cbxSel = (String) cbxCurso.getSelectedItem();
        if(cbxSel != null && !cbxSel.isEmpty()){
            String[] partes = cbxSel.split(" - ");
            int idCurso = Integer.parseInt(partes[0].trim());
            lblAsignaturaSel.setText(cbxSel);
            cargarTablaEstudiantes(idCurso);
        }
    }//GEN-LAST:event_cbxCursoActionPerformed

    private void btnGuardarCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarCambiosActionPerformed
        // ASEGURARSE DE QUE HAY UN CURSO SELECCIONADO;
        String cbxSel = (String) cbxCurso.getSelectedItem();
        if(cbxSel == null && cbxSel.isEmpty()){
            JOptionPane.showMessageDialog(this, "Debe seleccionar un curso.");
            return;
        }
        
        int idCurso = Integer.parseInt(cbxSel.split(" - ")[0].trim());
        DefaultTableModel model = (DefaultTableModel) tblListaEstudiante.getModel();
        
        // SI SE ESTA EDITANDO PAUSARLO ANTES DE GUARDARRRR
        if(tblListaEstudiante.isEditing()){
            tblListaEstudiante.getCellEditor().stopCellEditing();
        }
        
        int notasGuardadas = 0;
   
        for(int i=0; i<model.getRowCount(); i++){
            String cedula = model.getValueAt(i, 0).toString();
            Object nuevaNotaObj = model.getValueAt(i, 3);
            Object obser = model.getValueAt(i, 4);
            
            if(nuevaNotaObj != null && !nuevaNotaObj.toString().trim().isEmpty()){
                String nuevaNotaStr = nuevaNotaObj.toString().trim();
                String observacion;
                if(obser != null && !obser.toString().trim().isEmpty()){
                    observacion = obser.toString().trim();
                }else{
                    observacion = " ";
                }
                
                if(!nuevaNotaStr.isEmpty()){
                    try{
                        double nota = Double.parseDouble(nuevaNotaStr);
                        
                        //GUARDAR LA CALIIII
                        boolean exito = fachada.guardarCalificacion(cedula, idCurso, nota, observacion);
                        if(exito){
                            notasGuardadas++;
                        }
                    }catch (NumberFormatException e){
                        JOptionPane.showMessageDialog(this, "Ingrese un número válido ");
                    }catch (IllegalArgumentException e){
                        JOptionPane.showMessageDialog(this, "Estudiante  " + cedula + ": " + e.getMessage());
;
                    }
                }
            }
        }
        
        if(notasGuardadas > 0){
            JOptionPane.showMessageDialog(this, "Se guardaron: " + notasGuardadas + "calificación/es correctamente");
            cargarTablaEstudiantes(idCurso);
        }else{
            JOptionPane.showMessageDialog(this, "No se ingresó ninguna nueva calificación.");
        }
    }//GEN-LAST:event_btnGuardarCambiosActionPerformed

    private void btnVerHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerHistorialActionPerformed
        int filaSel = tblListaEstudiante.getSelectedRow();
        
        if(filaSel == -1){
            JOptionPane.showMessageDialog(this, "Seleccione un estudiante de la tabla primero.", "Atención", JOptionPane.WARNING_MESSAGE);
            return;
        }
        String cedula = tblListaEstudiante.getValueAt(filaSel, 0).toString();
        String nombreCompleto = tblListaEstudiante.getValueAt(filaSel, 1).toString() + " " + tblListaEstudiante.getValueAt(filaSel, 2).toString();
        Object itemCb = cbxCurso.getSelectedItem();
        if(itemCb == null){
            return;
        }
        int idCurso = Integer.parseInt(itemCb.toString().split(" - ")[0].trim());
        
        HistorialCalificacion historial = new HistorialCalificacion(this, cedula, nombreCompleto, "Activo", idCurso, fachada);
        historial.setVisible(true);
    }//GEN-LAST:event_btnVerHistorialActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        //DISEÑO FLATLAF VENTANA
        com.formdev.flatlaf.FlatLightLaf.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaDocente().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardarCambios;
    private javax.swing.JButton btnVerHistorial;
    private javax.swing.JComboBox<String> cbxCurso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAnioLectivo;
    private javax.swing.JLabel lblAsignaturaSel;
    private javax.swing.JLabel lblNomApe;
    private javax.swing.JPanel pnlBarraSuperior;
    private javax.swing.JPanel pnlCentral;
    private javax.swing.JPanel pnlInferior;
    private javax.swing.JPanel pnlPanelSuperior;
    private javax.swing.JPanel pnlVentana;
    private javax.swing.JTable tblListaEstudiante;
    // End of variables declaration//GEN-END:variables
}
