/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui_visual;

import fachada.SistemadeGestionAcademica;
import logica.entidades.Usuario;

/**
 *
 * @author iamx2
 */
public class Ventana extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Ventana.class.getName());

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPGeneral = new javax.swing.JPanel();
        jPBorder = new javax.swing.JPanel();
        lblSGA = new javax.swing.JLabel();
        lblSGAdescripcion = new javax.swing.JLabel();
        lblTaller = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblUsuario = new javax.swing.JLabel();
        CampoUsuario = new javax.swing.JTextField();
        lblContraseña = new javax.swing.JLabel();
        Login = new javax.swing.JButton();
        CampoContrasenia = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPGeneral.setBackground(new java.awt.Color(255, 255, 255));

        jPBorder.setBackground(java.awt.Color.black);

        javax.swing.GroupLayout jPBorderLayout = new javax.swing.GroupLayout(jPBorder);
        jPBorder.setLayout(jPBorderLayout);
        jPBorderLayout.setHorizontalGroup(
            jPBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPBorderLayout.setVerticalGroup(
            jPBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        lblSGA.setFont(new java.awt.Font("Arial Black", 1, 70)); // NOI18N
        lblSGA.setText("SGA");
        lblSGA.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblSGAdescripcion.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        lblSGAdescripcion.setText("SISTEMA DE GESTIÓN ACADÉMICA");
        lblSGAdescripcion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblTaller.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        lblTaller.setText("TALLER INTEGRADOR EN SISTEMAS");
        lblTaller.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jPanel1.setBackground(java.awt.Color.white);

        lblUsuario.setFont(new java.awt.Font("Yu Gothic", 1, 15)); // NOI18N
        lblUsuario.setText("USUARIO:");

        CampoUsuario.setToolTipText("");
        CampoUsuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        lblContraseña.setFont(new java.awt.Font("Yu Gothic", 1, 15)); // NOI18N
        lblContraseña.setText("CONTRASEÑA:");

        Login.setText("Ingresar");
        Login.addActionListener(this::LoginActionPerformed);

        CampoContrasenia.addActionListener(this::CampoContraseniaActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CampoUsuario)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(CampoContrasenia))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(Login)
                .addContainerGap(144, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CampoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblContraseña)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CampoContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(Login)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPGeneralLayout = new javax.swing.GroupLayout(jPGeneral);
        jPGeneral.setLayout(jPGeneralLayout);
        jPGeneralLayout.setHorizontalGroup(
            jPGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPBorder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPGeneralLayout.createSequentialGroup()
                .addGroup(jPGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPGeneralLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTaller))
                    .addGroup(jPGeneralLayout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addGroup(jPGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(lblSGAdescripcion)
                            .addComponent(lblSGA)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(172, Short.MAX_VALUE))
        );
        jPGeneralLayout.setVerticalGroup(
            jPGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPGeneralLayout.createSequentialGroup()
                .addComponent(jPBorder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTaller)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSGA, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSGAdescripcion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginActionPerformed
        String cedula = CampoUsuario.getText().trim();
        String password = new String(CampoContrasenia.getPassword());
        
        
        
        // Líneas de depuración:
        System.out.println("Cédula leída: [" + cedula + "]");
        System.out.println("Password leída: [" + password + "]");

        if (cedula.isEmpty() || password.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Completá usuario y contraseña", "Datos incompletos",
                javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        SistemadeGestionAcademica fachada = new SistemadeGestionAcademica();
        try {
            String resultado = fachada.validarLogin(cedula, password);

            if (resultado.equals(SistemadeGestionAcademica.LOGIN_OK)) {
                Usuario usuario = fachada.getUsuarioLogueado();
                javax.swing.JOptionPane.showMessageDialog(this,
                    "Bienvenido " + usuario.getNombre() + " (" + usuario.getRol() + ")",
                    "Login exitoso", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                // acá después: abrir la ventana correspondiente según usuario.getRol()
            } else if (resultado.equals(SistemadeGestionAcademica.LOGIN_USUARIO_INEXISTENTE)) {
                javax.swing.JOptionPane.showMessageDialog(this,
                    "No existe un usuario con esa cédula", "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            } else if (resultado.equals(SistemadeGestionAcademica.LOGIN_USUARIO_INACTIVO)) {
                javax.swing.JOptionPane.showMessageDialog(this,
                    "Este usuario está dado de baja", "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            } else if (resultado.equals(SistemadeGestionAcademica.LOGIN_PASSWORD_INCORRECTA)) {
                javax.swing.JOptionPane.showMessageDialog(this,
                    "Contraseña incorrecta", "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        } catch (java.sql.SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Error de conexión a la base de datos", "Error",
                javax.swing.JOptionPane.ERROR_MESSAGE);
            logger.log(java.util.logging.Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_LoginActionPerformed

    private void CampoContraseniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoContraseniaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoContraseniaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            System.out.println("MI HASH REAL: " + org.mindrot.jbcrypt.BCrypt.hashpw("123456", org.mindrot.jbcrypt.BCrypt.gensalt(10)));
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Ventana().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField CampoContrasenia;
    private javax.swing.JTextField CampoUsuario;
    private javax.swing.JButton Login;
    private javax.swing.JPanel jPBorder;
    private javax.swing.JPanel jPGeneral;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblContraseña;
    private javax.swing.JLabel lblSGA;
    private javax.swing.JLabel lblSGAdescripcion;
    private javax.swing.JLabel lblTaller;
    private javax.swing.JLabel lblUsuario;
    // End of variables declaration//GEN-END:variables
   
}
